// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddErrorQuestion(arg1:model.AddErrorQuestionReq):Promise<number>;

export function AddSysMenu(arg1:model.AddSysMenuDto):Promise<void>;

export function DeleteErrorQuestionById(arg1:number):Promise<void>;

export function DeleteMenuById(arg1:number):Promise<void>;

export function GetAllValidErrorQuestion():Promise<Array<model.SysErrorQuestion>>;

export function GetErrorQuestionByMenuId(arg1:number):Promise<Array<model.SysErrorQuestion>>;

export function GetFirstLevelMenuOption():Promise<Array<model.SelectOption>>;

export function GetMenuIdByPath(arg1:string):Promise<number>;

export function GetMenuTree():Promise<Array<model.MenuTreeDto>>;

export function GetSecondLevelMenuOption(arg1:number):Promise<Array<model.SelectOption>>;
