// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddErrorQuestion(arg1) {
  return window['go']['main']['App']['AddErrorQuestion'](arg1);
}

export function AddSysMenu(arg1) {
  return window['go']['main']['App']['AddSysMenu'](arg1);
}

export function DeleteErrorQuestionById(arg1) {
  return window['go']['main']['App']['DeleteErrorQuestionById'](arg1);
}

export function DeleteMenuById(arg1) {
  return window['go']['main']['App']['DeleteMenuById'](arg1);
}

export function GetAllValidErrorQuestion() {
  return window['go']['main']['App']['GetAllValidErrorQuestion']();
}

export function GetErrorQuestionByMenuId(arg1) {
  return window['go']['main']['App']['GetErrorQuestionByMenuId'](arg1);
}

export function GetFirstLevelMenuOption() {
  return window['go']['main']['App']['GetFirstLevelMenuOption']();
}

export function GetMenuIdByPath(arg1) {
  return window['go']['main']['App']['GetMenuIdByPath'](arg1);
}

export function GetMenuTree() {
  return window['go']['main']['App']['GetMenuTree']();
}

export function GetSecondLevelMenuOption(arg1) {
  return window['go']['main']['App']['GetSecondLevelMenuOption'](arg1);
}
